
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';

const LegalInfo = () => {
  return (
    <div className="grid gap-4">
      <Card>
        <CardHeader>
          <CardTitle>Terms of Service</CardTitle>
          <CardDescription>Last updated: April 5, 2025</CardDescription>
        </CardHeader>
        <CardContent className="text-sm space-y-4">
          <div>
            <h3 className="font-semibold mb-2">1. Acceptance of Terms</h3>
            <p>
              By accessing and using the NNticks platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please refrain from using our Service.
            </p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">2. Description of Service</h3>
            <p>
              NNticks provides a neural network-based market analysis and prediction platform. The Service includes real-time data streaming, predictive analytics, and trading assistance tools.
            </p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">3. Use of Service</h3>
            <p>
              You agree to use the Service only for purposes that are permitted by these Terms and any applicable law or regulation. You are solely responsible for all of your activity in connection with the Service.
            </p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">4. Disclaimer</h3>
            <p>
              The Service is provided on an "as is" and "as available" basis. NNticks makes no warranties, expressed or implied, and hereby disclaims all warranties, including without limitation warranties of merchantability, fitness for a particular purpose, or non-infringement.
            </p>
            <p className="mt-2">
              Financial markets involve risk, and past performance is not indicative of future results. NNticks does not guarantee the accuracy or completeness of predictions.
            </p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">5. Limitation of Liability</h3>
            <p>
              In no event shall NNticks be liable for any damages whatsoever, including but not limited to any direct, indirect, special, incidental, consequential, or exemplary damages resulting from the use or inability to use the Service or any content thereon.
            </p>
          </div>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader>
          <CardTitle>Privacy Policy</CardTitle>
          <CardDescription>Last updated: April 5, 2025</CardDescription>
        </CardHeader>
        <CardContent className="text-sm space-y-4">
          <div>
            <h3 className="font-semibold mb-2">1. Information Collection</h3>
            <p>
              We collect information you provide directly to us, such as account information, preferences, and trading data. We also collect data about your usage of the platform and technical information.
            </p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">2. Use of Information</h3>
            <p>
              We use the information we collect to operate, maintain, and improve our Service, to provide personalized predictions, and to communicate with you.
            </p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">3. Data Storage</h3>
            <p>
              Your data is stored securely using Supabase infrastructure. We implement appropriate technical and organizational measures to protect your personal information.
            </p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">4. Data Sharing</h3>
            <p>
              We do not sell your personal information. We may share data with trusted partners to help perform statistical analysis or provide customer support.
            </p>
          </div>
          
          <div>
            <h3 className="font-semibold mb-2">5. Your Rights</h3>
            <p>
              You have the right to access, correct, or delete your personal information. You may also request a copy of your data that we have on file.
            </p>
          </div>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader>
          <CardTitle>Disclaimer</CardTitle>
        </CardHeader>
        <CardContent className="text-sm space-y-4">
          <p>
            NNticks is a tool designed to assist with market analysis and predictions. It is not intended to be used as the sole basis for any investment decision. The financial markets involve risk, and past performance is not indicative of future results.
          </p>
          <p>
            The predictions generated by our neural network models are based on historical data and mathematical algorithms. While we strive for accuracy, we cannot guarantee the reliability of these predictions or their applicability to specific market conditions.
          </p>
          <p>
            Users are advised to conduct their own research and consider consulting with qualified financial professionals before making investment decisions. NNticks shall not be liable for any losses incurred based on information provided through our Service.
          </p>
          <Separator className="my-4" />
          <p className="font-semibold">
            © 2025 NNticks Enterprise Analytics. All rights reserved.
          </p>
        </CardContent>
      </Card>
    </div>
  );
};

export default LegalInfo;
