// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsuaodgnofwagsvsbnjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdWFvZGdub2Z3YWdzdnNibmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDM3NzIsImV4cCI6MjA1OTAxOTc3Mn0.cqCay9zShrybHQqf8QWmn02IIQuRuW8r2efFjyXmmnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);